export const allRecordings = [
  {
    class: "dataBase",
    title: "Primera Clase",
    date: "03-04-2024",
    teacher: "Gustavo Virtos",
    img: "/video-base.webp",
    link: "https://www.youtube.com/watch?v=J8v2z4pQTxs",
  },
  {
    class: "dataBase",
    title: "Segunda Clase",
    date: "08-04-2024",
    teacher: "Gustavo Virtos",
    img: "/video-base.webp",
    link: "https://www.youtube.com/watch?v=mOPjMCj6ygw",
  },
  {
    class: "dataBase",
    title: "Tercera Clase",
    date: "10-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=gQcpRmzJcPc",
  },
  {
    class: "dataBase",
    title: "Cuarta Clase",
    date: "15-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=U6CkYfExWto",
  },
  {
    class: "dataBase",
    title: "Quinta Clase",
    date: "18-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=XKJh83HJOcg",
  },
  // --------------------------------------------------------------
  {
    class: "logic",
    title: "Leyes Lógicas (Parte 1)",
    date: "09-04-2024",
    img: "/video-logica.webp",
    teacher: "María Alicia Piñeiro",
    link: "https://www.youtube.com/watch?v=mr3WoEhFQAM",
  },
  {
    class: "logic",
    title: "Leyes Lógicas (Parte 2)",
    date: "09-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",

    link: "https://www.youtube.com/watch?v=djlLOqJEWIA",
  },
  {
    class: "logic",
    title: "Leyes Lógicas (Parte 3)",
    date: "09-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=-eFaCpecjtc",
  },
  {
    class: "logic",
    title: "Funciones proposicionales (Parte 1)",
    date: "16-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=bA3OvkZpgFY",
  },
  {
    class: "logic",
    title: "Funciones proposicionales (Parte 2)",
    date: "16-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=aI-G5V-IGfA",
  },

  {
    class: "mathematical",
    title: "Primera Clase (Parte 1)",
    date: "04-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=Wu5NaHW4HTA",
  },
  {
    class: "mathematical",
    title: "Primera Clase (Parte 2)",
    date: "04-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=1ezz92xfX8Y",
  },
  {
    class: "mathematical",
    title: "Repaso de tarea anterior (Parte 1)",
    date: "11-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "https://youtu.be/oaoG3J8P7XI",
  },
  {
    class: "mathematical",
    title: "Repaso de tarea anterior (Parte 2)",
    date: "11-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "https://youtu.be/Qz6sisPGdcE",
  },
  {
    class: "mathematical",
    title: "Repaso con actividades nuevas",
    date: "18-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "https://youtu.be/4diGN3AepV0",
  },

  {
    class: "technique",
    title: "Clase introductoria de Python",
    date: "05-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=Y6132WfbxnE",
  },
  {
    class: "technique",
    title: "Funcion Print() de Python",
    date: "08-04-2024",
    img: "/video-tecnica.webp",
    teacher: "Fernando Melissani",
    link: "https://www.youtube.com/watch?v=496qc6IA7qo",
  },
  {
    class: "technique",
    title: "Tipos de datos de Python",
    date: "12-04-2024",
    img: "/video-tecnica.webp",
    teacher: "Fernando Melissani",
    link: "https://www.youtube.com/watch?v=QLn8OmS-ZJA",
  },
  {
    class: "technique",
    title: "Operadores de Python",
    date: "15-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=CtNcRtcQ950",
  },
];
