export const allRecordings = [
  {
    subject: "dataBase",
    title: "Primera Clase",
    date: "03-04-2024",
    teacher: "Gustavo Virtos",
    img: "/video-base.webp",
    link: "https://www.youtube.com/watch?v=J8v2z4pQTxs",
  },
  {
    subject: "dataBase",
    title: "Segunda Clase",
    date: "08-04-2024",
    teacher: "Gustavo Virtos",
    img: "/video-base.webp",
    link: "https://www.youtube.com/watch?v=mOPjMCj6ygw",
  },
  {
    subject: "dataBase",
    title: "Tercera Clase",
    date: "10-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=gQcpRmzJcPc",
  },
  {
    subject: "dataBase",
    title: "Cuarta Clase",
    date: "15-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=U6CkYfExWto",
  },
  {
    subject: "dataBase",
    title: "Quinta Clase",
    date: "18-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=XKJh83HJOcg",
  },
  {
    subject: "dataBase",
    title: "Sexta Clase",
    date: "24-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=OdNqXiUQDsU",
  },

  // --------------------------------------------------------------
  {
    subject: "logic",
    title: "Leyes Lógicas (Parte 1)",
    date: "09-04-2024",
    img: "/video-logica.webp",
    teacher: "María Alicia Piñeiro",
    link: "https://www.youtube.com/watch?v=mr3WoEhFQAM",
  },
  {
    subject: "logic",
    title: "Leyes Lógicas (Parte 2)",
    date: "09-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",

    link: "https://www.youtube.com/watch?v=djlLOqJEWIA",
  },
  {
    subject: "logic",
    title: "Leyes Lógicas (Parte 3)",
    date: "09-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=-eFaCpecjtc",
  },
  {
    subject: "logic",
    title: "Lógica de predicados (Parte 1)",
    date: "16-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=bA3OvkZpgFY",
  },
  {
    subject: "logic",
    title: "Lógica de predicados (Parte 2)",
    date: "16-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=aI-G5V-IGfA",
  },
  {
    subject: "logic",
    title: "Repaso antes del parcial",
    date: "23-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=TZT12GccQYk",
  },

  {
    subject: "mathematical",
    title: "Primera Clase (Parte 1)",
    date: "04-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://www.youtube.com/watch?v=Wu5NaHW4HTA",
  },
  {
    subject: "mathematical",
    title: "Primera Clase (Parte 2)",
    date: "04-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://www.youtube.com/watch?v=1ezz92xfX8Y",
  },
  {
    subject: "mathematical",
    title: "Repaso de tarea anterior (Parte 1)",
    date: "11-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/oaoG3J8P7XI",
  },
  {
    subject: "mathematical",
    title: "Repaso de tarea anterior (Parte 2)",
    date: "11-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/Qz6sisPGdcE",
  },
  {
    subject: "mathematical",
    title: "Repaso con actividades nuevas",
    date: "18-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/4diGN3AepV0",
  },
  {
    subject: "mathematical",
    title: "Actividades y nuevos temas (Parte 1)",
    date: "25-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/LpyBkUwOOmA",
  },
  {
    subject: "mathematical",
    title: "Actividades y nuevos temas (Parte 2)",
    date: "25-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/QRGq64_wIGk",
  },

  {
    subject: "technique",
    title: "Clase introductoria",
    date: "05-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=Y6132WfbxnE",
  },
  {
    subject: "technique",
    title: "Funcion Print() de Python",
    date: "08-04-2024",
    img: "/video-tecnica.webp",
    teacher: "Fernando Melissani",
    link: "https://www.youtube.com/watch?v=496qc6IA7qo",
  },
  {
    subject: "technique",
    title: "Tipos de datos de Python",
    date: "12-04-2024",
    img: "/video-tecnica.webp",
    teacher: "Fernando Melissani",
    link: "https://www.youtube.com/watch?v=QLn8OmS-ZJA",
  },
  {
    subject: "technique",
    title: "Operadores y variables",
    date: "15-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=CtNcRtcQ950",
  },
  {
    subject: "technique",
    title: "Comentarios e input()",
    date: "19-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/lXkyl7c8M2E",
  },
  {
    subject: "technique",
    title: "Decisiones en Python 1",
    date: "22-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=tmAiDgwWYuM",
  },
  {
    subject: "technique",
    title: "Decisiones en Python 2",
    date: "26-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/2tPeHSxXxF0",
  },
];
