export const allRecordings = [
  {
    subject: "dataBase",
    title: "Primera Clase",
    date: "03-04-2024",
    teacher: "Gustavo Virtos",
    img: "/video-base.webp",
    link: "https://www.youtube.com/watch?v=J8v2z4pQTxs",
  },
  {
    subject: "dataBase",
    title: "Segunda Clase",
    date: "08-04-2024",
    teacher: "Gustavo Virtos",
    img: "/video-base.webp",
    link: "https://www.youtube.com/watch?v=mOPjMCj6ygw",
  },
  {
    subject: "dataBase",
    title: "Tercera Clase",
    date: "10-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=gQcpRmzJcPc",
  },
  {
    subject: "dataBase",
    title: "Cuarta Clase",
    date: "15-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=U6CkYfExWto",
  },
  {
    subject: "dataBase",
    title: "Quinta Clase",
    date: "18-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=XKJh83HJOcg",
  },
  {
    subject: "dataBase",
    title: "Sexta Clase",
    date: "24-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=OdNqXiUQDsU",
  },
  {
    subject: "dataBase",
    title: "Septima Clase",
    date: "29-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=TTO4d6FYSsw",
  },
  {
    subject: "dataBase",
    title: "Octava Clase",
    date: "06-05-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=SQP96ndeyss",
  },
  {
    subject: "dataBase",
    title: "Novena Clase",
    date: "08-05-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=AWIS9I9gjEI",
  },
  {
    subject: "dataBase",
    title: "Décima Clase",
    date: "13-05-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://www.youtube.com/watch?v=uz5FFxHj_2g",
  },
  {
    subject: "dataBase",
    title: "Undécima Clase",
    date: "15-05-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://youtu.be/2SWBogRD2PY",
  },

  {
    subject: "dataBase",
    title: "Duodécima Clase",
    date: "20-05-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://youtu.be/wy8Uc-MMpN8",
  },
  {
    subject: "dataBase",
    title: "Decimotercera Clase 1",
    date: "22-05-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://youtu.be/WpN5x5Tn8mU",
  },
  {
    subject: "dataBase",
    title: "Decimotercera Clase 2",
    date: "22-05-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://youtu.be/XRhtOa9E8Qk",
  },

  // --------------------------------------------------------------
  {
    subject: "logic",
    title: "Leyes Lógicas (Parte 1)",
    date: "09-04-2024",
    img: "/video-logica.webp",
    teacher: "María Alicia Piñeiro",
    link: "https://www.youtube.com/watch?v=mr3WoEhFQAM",
  },
  {
    subject: "logic",
    title: "Leyes Lógicas (Parte 2)",
    date: "09-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",

    link: "https://www.youtube.com/watch?v=djlLOqJEWIA",
  },
  {
    subject: "logic",
    title: "Leyes Lógicas (Parte 3)",
    date: "09-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=-eFaCpecjtc",
  },
  {
    subject: "logic",
    title: "Lógica de predicados (Parte 1)",
    date: "16-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=bA3OvkZpgFY",
  },
  {
    subject: "logic",
    title: "Lógica de predicados (Parte 2)",
    date: "16-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=aI-G5V-IGfA",
  },
  {
    subject: "logic",
    title: "Repaso antes del parcial",
    date: "23-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=TZT12GccQYk",
  },
  {
    subject: "logic",
    title: "Razonamiento 1 (Parte 1)",
    date: "14-05-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=JP71GZcE-QU&feature=youtu.be",
  },

  {
    subject: "logic",
    title: "Razonamiento 1 (Parte 2)",
    date: "14-05-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://youtu.be/axHjswxTndo",
  },

  {
    subject: "logic",
    title: "Razonamiento 2",
    date: "21-05-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=mDVGMZiLb1I",
  },

  // --------------------------------------------------------
  {
    subject: "mathematical",
    title: "Primera Clase (Parte 1)",
    date: "04-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://www.youtube.com/watch?v=Wu5NaHW4HTA",
  },
  {
    subject: "mathematical",
    title: "Primera Clase (Parte 2)",
    date: "04-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://www.youtube.com/watch?v=1ezz92xfX8Y",
  },
  {
    subject: "mathematical",
    title: "Repaso de tarea anterior (Parte 1)",
    date: "11-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/oaoG3J8P7XI",
  },
  {
    subject: "mathematical",
    title: "Repaso de tarea anterior (Parte 2)",
    date: "11-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/Qz6sisPGdcE",
  },
  {
    subject: "mathematical",
    title: "Repaso con actividades nuevas",
    date: "18-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/4diGN3AepV0",
  },
  {
    subject: "mathematical",
    title: "Actividades y nuevos temas (Parte 1)",
    date: "25-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/LpyBkUwOOmA",
  },
  {
    subject: "mathematical",
    title: "Actividades y nuevos temas (Parte 2)",
    date: "25-04-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://youtu.be/QRGq64_wIGk",
  },
  {
    subject: "mathematical",
    title: "Sistema de ecuaciones (Parte 1)",
    date: "02-05-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://www.youtube.com/watch?v=31lfVXE4B5c",
  },
  {
    subject: "mathematical",
    title: "Sistema de ecuaciones (Parte 2)",
    date: "02-05-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://www.youtube.com/watch?v=PQqFWsew6oM",
  },

  {
    subject: "mathematical",
    title: "Repaso antes del parcial (Parte 1)",
    date: "09-05-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://www.youtube.com/watch?v=NvzXc7AVdpw",
  },
  {
    subject: "mathematical",
    title: "Repaso antes del parcial (Parte 2)",
    date: "09-05-2024",
    teacher: "Graciela Medici",
    img: "/video-matematica.webp",
    link: "https://www.youtube.com/watch?v=K4fDNUxnZbw",
  },

  // -----------------------------------
  {
    subject: "technique",
    title: "Clase introductoria",
    date: "05-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=Y6132WfbxnE",
  },
  {
    subject: "technique",
    title: "Funcion Print() de Python",
    date: "08-04-2024",
    img: "/video-tecnica.webp",
    teacher: "Fernando Melissani",
    link: "https://www.youtube.com/watch?v=496qc6IA7qo",
  },
  {
    subject: "technique",
    title: "Tipos de datos de Python",
    date: "12-04-2024",
    img: "/video-tecnica.webp",
    teacher: "Fernando Melissani",
    link: "https://www.youtube.com/watch?v=QLn8OmS-ZJA",
  },
  {
    subject: "technique",
    title: "Operadores y variables",
    date: "15-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=CtNcRtcQ950",
  },
  {
    subject: "technique",
    title: "Comentarios e input()",
    date: "19-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/lXkyl7c8M2E",
  },
  {
    subject: "technique",
    title: "Decisiones en Python 1",
    date: "22-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=tmAiDgwWYuM",
  },
  {
    subject: "technique",
    title: "Decisiones en Python 2",
    date: "26-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/2tPeHSxXxF0",
  },
  {
    subject: "technique",
    title: "Metodos y funciones",
    date: "29-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/pnGFixUcHhE",
  },
  {
    subject: "technique",
    title: "Listas (Parte 1)",
    date: "03-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/gkc5G-jCOoE",
  },
  {
    subject: "technique",
    title: "Listas (Parte 2)",
    date: "03-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/DraWPsZ99TI",
  },

  {
    subject: "technique",
    title: "Tuplas y diccionarios",
    date: "06-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/iyYdQoid0rA",
  },

  {
    subject: "technique",
    title: "Actividad de tuplas y diccionarios",
    date: "10-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=77rYebjUDdI",
  },

  {
    subject: "technique",
    title: "Excepciones",
    date: "13-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=dnAfYbFXcRU",
  },

  {
    subject: "technique",
    title: "Funciones",
    date: "17-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://www.youtube.com/watch?v=M3nFiZzZpuk",
  },

  {
    subject: "technique",
    title: "Practica de Parcial 1",
    date: "20-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/kwk7F7FD5UQ",
  },

  {
    subject: "technique",
    title: "Practica de Parcial 2",
    date: "20-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/kwk7F7FD5UQ",
  },
  // #---------------------------
  {
    subject: "logic",
    title: "Logica digital (Parte 1)",
    date: "28-05-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=qtW8I2WGm4U",
  },
  {
    subject: "logic",
    title: "Logica digital (Parte 2)",
    date: "28-05-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?si=rWdUwky7_s5pDX7V&v=euHMAYHVAc8&feature=youtu.be",
  },
  {
    subject: "logic",
    title: "Diagrama logico con compuertas (Parte 1)",
    date: "04-06-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=u3kwAE1yOuk&list=PLBblByh1oPEdNvwitlWqJKkh3T1euI6Lc&index=11",
  },
  {
    subject: "logic",
    title: "Diagrama logico con compuertas (Parte 2)",
    date: "04-06-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "https://www.youtube.com/watch?v=qN7xXfPmHx0",
  },

  {
    subject: "dataBase",
    title: "Ejercicios de MER",
    date: "27-05-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://youtu.be/E7WaYVXkQu0",
  },
  {
    subject: "dataBase",
    title: "Correcion de Prueba",
    date: "03-06-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://youtu.be/XG-DR_MeDV4",
  },
  {
    subject: "dataBase",
    title: "Ejercicios de MR - (Parte 1)",
    date: "05-06-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://youtu.be/b7s0giyXlwo",
  },
  {
    subject: "dataBase",
    title: "Ejercicios de MR - (Parte 2)",
    date: "05-06-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "https://youtu.be/PfBbQm-YOhU",
  },

  {
    subject: "technique",
    title: "Repaso de TP",
    date: "27-05-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/5rZ9cbYHZuM",
  },
  {
    subject: "technique",
    title: "Entorno Virtual",
    date: "03-06-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/GbaOYTg-s_Q",
  },
  {
    subject: "technique",
    title: "Dependencia OS",
    date: "07-06-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "https://youtu.be/Aynjl8FW-94",
  },
];
