export const allRecordings = [
  {
    subject: "dataBase",
    videoId: "datos1",
    title: "Primera Clase",
    date: "03-04-2024",
    teacher: "Gustavo Virtos",
    img: "/video-base.webp",
    link: "J8v2z4pQTxs",
  },
  {
    subject: "dataBase",
    videoId: "datos2",
    title: "Segunda Clase",
    date: "08-04-2024",
    teacher: "Gustavo Virtos",
    img: "/video-base.webp",
    link: "mOPjMCj6ygw",
  },
  {
    subject: "dataBase",
    videoId: "datos3",
    title: "Tercera Clase",
    date: "10-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "gQcpRmzJcPc",
  },
  {
    subject: "dataBase",
    videoId: "datos4",
    title: "Cuarta Clase",
    date: "15-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "U6CkYfExWto",
  },
  {
    subject: "dataBase",
    videoId: "datos5",
    title: "Quinta Clase",
    date: "18-04-2024",
    img: "/video-base.webp",
    teacher: "Gustavo Virtos",
    link: "XKJh83HJOcg",
  },
  // --------------------------------------------------------------
  {
    subject: "logic",
    videoId: "logica1",
    title: "Leyes Lógicas (Parte 1)",
    date: "09-04-2024",
    img: "/video-logica.webp",
    teacher: "María Alicia Piñeiro",
    link: "mr3WoEhFQAM",
  },
  {
    subject: "logic",
    videoId: "logica2",
    title: "Leyes Lógicas (Parte 2)",
    date: "09-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "djlLOqJEWIA",
  },
  {
    videoId: "logica3",
    subject: "logic",
    title: "Leyes Lógicas (Parte 3)",
    date: "09-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "-eFaCpecjtc",
  },
  {
    subject: "logic",
    videoId: "logica4",
    title: "Funciones proposicionales (Parte 1)",
    date: "16-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "bA3OvkZpgFY",
  },
  {
    subject: "logic",
    videoId: "logica5",
    title: "Funciones proposicionales (Parte 2)",
    date: "16-04-2024",
    teacher: "María Alicia Piñeiro",
    img: "/video-logica.webp",
    link: "aI-G5V-IGfA",
  },

  {
    subject: "mathematical",
    videoId: "matematica1",
    title: "Primera Clase (Parte 1)",
    date: "04-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "Wu5NaHW4HTA",
  },
  {
    subject: "mathematical",
    videoId: "matematica2",
    title: "Primera Clase (Parte 2)",
    date: "04-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "1ezz92xfX8Y",
  },
  {
    subject: "mathematical",
    videoId: "matematica3",
    title: "Repaso de tarea anterior (Parte 1)",
    date: "11-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "oaoG3J8P7XI",
  },
  {
    subject: "mathematical",
    videoId: "matematica4",
    title: "Repaso de tarea anterior (Parte 2)",
    date: "11-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "Qz6sisPGdcE",
  },
  {
    subject: "mathematical",
    videoId: "matematica5",
    title: "Repaso con actividades nuevas",
    date: "18-04-2024",
    teacher: "Graciela Medici",
    img: "/video-logica.webp",
    link: "4diGN3AepV0",
  },

  {
    subject: "technique",
    videoId: "tecnica1",
    title: "Clase introductoria de Python",
    date: "05-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "Y6132WfbxnE",
  },
  {
    subject: "technique",
    videoId: "tecnica2",
    title: "Funcion Print() de Python",
    date: "08-04-2024",
    img: "/video-tecnica.webp",
    teacher: "Fernando Melissani",
    link: "496qc6IA7qo",
  },
  {
    subject: "technique",
    videoId: "tecnica3",
    title: "Tipos de datos de Python",
    date: "12-04-2024",
    img: "/video-tecnica.webp",
    teacher: "Fernando Melissani",
    link: "QLn8OmS-ZJA",
  },
  {
    subject: "technique",
    videoId: "tecnica4",
    title: "Operadores de Python",
    date: "15-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "CtNcRtcQ950",
  },

  {
    subject: "technique",
    videoId: "tecnica5",
    title: "Más operadores de Python",
    date: "20-04-2024",
    teacher: "Fernando Melissani",
    img: "/video-tecnica.webp",
    link: "lXkyl7c8M2E",
  },
];
